version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env
    volumes:
      - ./docker/mysql_data:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    command: "python3 app.py"
    volumes:
      - .:/code
    depends_on:
      - db
